# Generated by Django 3.2.5 on 2021-07-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('category', models.CharField(max_length=128, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('city', models.CharField(max_length=64, verbose_name='Cidade')),
                ('state', models.CharField(max_length=64, verbose_name='Estado')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('value', models.FloatField(verbose_name='valor')),
                ('set_date', models.DateField(blank=True, null=True, verbose_name='Data de Marcação')),
                ('set_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Marcação')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['id'],
            },
        ),
    ]
