# Generated by Django 3.2.4 on 2021-09-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='service',
            name='state',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Estado'),
        ),
    ]
