# Generated by Django 3.2.5 on 2021-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_search', models.CharField(max_length=128, verbose_name='Busca_serviço')),
                ('city_search', models.CharField(max_length=64, verbose_name='Busca_serviço')),
                ('category_search', models.CharField(max_length=128, verbose_name='Busca_serviço')),
                ('state_search', models.CharField(max_length=64, verbose_name='Busca_serviço')),
            ],
            options={
                'verbose_name': 'Busca',
                'verbose_name_plural': 'Buscas',
                'ordering': ['id'],
            },
        ),
    ]
