# Generated by Django 3.2.5 on 2021-09-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=16, verbose_name='CPF')),
                ('place', models.CharField(max_length=255, verbose_name='Endereço')),
                ('number', models.CharField(max_length=6, verbose_name='Número')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('district', models.CharField(max_length=64, verbose_name='Bairro')),
                ('city', models.CharField(max_length=64, verbose_name='Cidade')),
                ('state', models.CharField(max_length=64, verbose_name='Estado')),
                ('phone', models.CharField(max_length=16, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Dados Pessoal',
                'verbose_name_plural': 'Dados Pessoais',
                'ordering': ['id'],
            },
        ),
    ]
